apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-1
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook-1
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: argocd
    repoURL: "https://github.com/bgslopes/Argocd.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true